### ISSUE TITLE
Can't see edges in graph.jl

### ISSUE THREAD

**Issue by sbacelar** [h-Klok/StatsWithJuliaBook#13]
I can't see the edges in `graph.jl` in 1_chapter. 
I tried to run the file both with Atom Juno and Jupyter Lab.

**Comment by h-Klok** [comment]
hi @sbacelar, the code has been changed a bit since middle of this year, including changing over to Plots.jl. I've just updated this code example on github and checked that it works on Julia 1.3.0. Note that now the example will actually save the output to a file, rather than just display it (the results are saved as graph.gif). If you open this file in your web browser, such as firefox, then you should be able to see the animation.

Will tentatively close this ticket now as resolved, but if it is still a problem please feel free to re-open, thanks :)
