### ISSUE TITLE
use julia plotting library

### ISSUE THREAD

**Issue by waynelapierre** [h-Klok/StatsWithJuliaBook#22]
I really like your book but I personally prefer using Julia plotting packages instead of the pyplot.

**Comment by yoninazarathy** [comment]
The choice to stick with `pyplot()` was due to the fact that at time time of creation other backends were not as mature. In a future version we may modify out of pyplot and readers using the code can certainly make the change themselves. Keep in mind that when we started working on the book `Plots.jl` itself was still not mature enough (as it is today).
